### ISSUE TITLE
Create a society is not working

### ISSUE THREAD

**Issue by BlessingD** [AdeelH/reddit-clone#2]
Hi i tried creating a society from both the user side and the admin side but it just says "Sorry, nothing here" every time and it doesn't display the society anywhere. I checked the database and the societies I have created are there but on the user/admin end, nothing shows.

May you please assist.thanks

**Comment by AdeelH** [comment]
Hi, it's been a long time since I worked with this code, but last I checked everything seemed to be working. At this point, if you are using it, you are probably more familiar with the code than I am! So I would suggest some good ol' fashioned debugging!

That said, trying to access the society's page directly by passing the `soc` parameter in the query string (".../soc.php?soc=<name>") might be a good place to start.
